//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication42.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModels : DbContext
    {
        public DBModels()
            : base("name=DBModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<organizer> organizers { get; set; }
        public virtual DbSet<req_addr> req_addr { get; set; }
        public virtual DbSet<req_desc> req_desc { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<vol_addr> vol_addr { get; set; }
        public virtual DbSet<volunteerlogin> volunteerlogins { get; set; }
        public virtual DbSet<volunteer> volunteers { get; set; }
    }
}
