//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication42.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestresource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requestresource()
        {
            this.requsetaddresses = new HashSet<requsetaddress>();
        }
    
        public int RequestID { get; set; }
        public int Amount { get; set; }
        public string Description { get; set; }
        public int Delivered { get; set; }
        public int EventID { get; set; }
        public int ResourceID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual eve eve { get; set; }
        public virtual resourcetype resourcetype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requsetaddress> requsetaddresses { get; set; }
    }
}
