//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication42.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requsetaddress
    {
        public int ReqAddID { get; set; }
        public string street { get; set; }
        public string street2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public int RequestID { get; set; }
    
        public virtual requestresource requestresource { get; set; }
    }
}
