//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace WebApplication42.Models
{
    public class voltab
    {
        //VRID 

        [Required(ErrorMessage = "An amount is required")]
        [Range (1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int Amount { get; set; }

        [Required(ErrorMessage = "A description is required")]
        [StringLength(256, ErrorMessage = "Must be between 5 and 256 characters", MinimumLength = 5)]
        public string Description { get; set; }

        public int Delivered { get; set; }

        public int UserID { get; set; }

        public int ResourceID { get; set; }

        public int EventID { get; set; }

        public SelectList resourceList { get; set; }
    }
}